# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Modified version of the original code:
#  Project: https://manski.net/2016/09/vagrant-multi-machine-tutorial/#endresult
#  Author: Sebastian Krysmanski
#

BOX_IMAGE = "bento/ubuntu-20.04"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    # Setting up private_network to have virtual host
    subconfig.vm.network :private_network, ip: "192.168.33.10"
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      # Setting up private_network to have virtual host
      subconfig.vm.network :private_network, ip: "192.168.33.#{i + 10}"
    end
  end
  
  # Enable ssh forward agent
  config.ssh.forward_agent = true

  # Install ifconfig on all machines  
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get install -y net-tools
  SHELL
end
